### ISSUE TITLE
Suggestion: Add another modification mode to mimic in-game options

### ISSUE THREAD

**Issue by tophattwaffle** [Reezonate/EasyOffset#5]
Feel free to close if you don't want feature requests.

I think it may be nice to have another option in the drop down which would give you the sliders that mimic the in-game stock options. 

A lot of profiles online are given in the normal X,Y,Z, X DEG, Y DEG, Z DEG. Having the option in easy offset to plug these values in as a starting point would be convenient.

**Comment by Reezonate** [comment]
Sounds interesting, I'll experiment with that and see if it fits.

The problem is that in-game settings work differently between Oculus mode and SteamVR, which adds a lot of ambiguity when it comes to profiles from the internet.
In EasyOffset on the other hand there is no difference and the config looks the same regardless of the VR platform you use.

**Comment by Reezonate** [comment]
I tried to add this mode and it was very confusing seeing different values on sliders across different adjustment modes. But if you really want to, you can plug config from the internet into the base game settings or SaberTailor and then use config migration settings to import it into EasyOffset

Thanks for the suggestion anyway!
